### ISSUE TITLE
Deploy script

### ISSUE THREAD

**Issue by vmikhav** [sungmaster/teajudge#1]
- [x] check/install build essential, python3, php (7.1?), mysql
- [x] ask interface language ( English, Ukrainian and Russian now )
- [x] ask database host ( localhost as default )
- [x] ask database admin login and password
- [x] import database structure ( teajudge.sql )
  ```bash
  mysql -h "server-name" -u "root" "-pXXXXXXXX" < "teajudge.sql"
  ```
- [x] create database user ( login : teajudge, password : random string )
  ```mysql
  CREATE USER 'teajudge'@'localhost' IDENTIFIED BY 'new_password';
  GRANT SELECT, INSERT, UPDATE, DELETE ON teajudge.* TO 'teajudge'@'localhost';
  FLUSH PRIVILEGES;
  ```
- [x] write sensetive data to php/sensetive_data.php ( database user login and password, interface language and token secret as random string )
  ```bash
  pass='password'
  sed -i "s/define('TJSECRET', '.*')/define('TJSECRET', '${pass}')/" ./php/sensetive_data.php
  ```
- [x] exec this code 
  ```bash
  cd ./sandbox/libsandbox 
  ./configure
  sudo make install --prefix=/usr --libdir=/usr/lib
  cd ../pysandbox
  python3 setup.py build
  sudo python3 setup.py install
  ```

**Comment by VTurturika** [comment]
[Dialog utility](http://www.linuxjournal.com/article/2807)

**Comment by VTurturika** [comment]
Checking if popular web servers are running
``sudo netstat -ntlp | grep /nginx``
``sudo netstat -ntlp | grep /apache2``
``sudo netstat -ntlp | grep /lighttpd``
